import assert from "node:assert/strict";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { spawnSync } from "node:child_process";
import test from "node:test";
import {
  buildSystemEntry,
  findExecutable,
  installSystemEntry,
  resolveDefaultBinDir,
} from "../dist/system-entry.js";

function fixture(t) {
  const root = fs.mkdtempSync(path.join(os.tmpdir(), "asvc-entry-"));
  t.after(() => fs.rmSync(root, { recursive: true, force: true }));
  const runtimeBin = path.join(root, "runtime", "bin");
  const stableBin = path.join(root, "stable", "bin");
  fs.mkdirSync(runtimeBin, { recursive: true });
  fs.mkdirSync(stableBin, { recursive: true });

  const node = path.join(runtimeBin, "node");
  const cli = path.join(runtimeBin, "asvc-cli");
  fs.writeFileSync(node, '#!/bin/sh\ncli="$1"\nshift\nexec "$cli" "$@"\n', { mode: 0o755 });
  fs.writeFileSync(cli, '#!/bin/sh\nprintf "resolved:%s\\n" "$*"\n', { mode: 0o755 });
  return { root, runtimeBin, stableBin, node, cli };
}

test("findExecutable resolves from a minimal PATH without shell profiles", (t) => {
  const { runtimeBin, node } = fixture(t);
  assert.equal(findExecutable("node", { PATH: `${runtimeBin}:/usr/bin:/bin` }), node);
  assert.equal(findExecutable("asvc", { PATH: "/usr/bin:/bin" }), undefined);
});

test("default entry location uses brew when present and otherwise does not require asdf", (t) => {
  const { root, runtimeBin } = fixture(t);
  const brew = path.join(runtimeBin, "brew");
  fs.writeFileSync(brew, `#!/bin/sh\nprintf %s ${JSON.stringify(root)}\n`, { mode: 0o755 });
  assert.equal(
    resolveDefaultBinDir({ PATH: `${runtimeBin}:/usr/bin:/bin`, HOME: root }),
    path.join(root, "bin")
  );
  assert.equal(
    resolveDefaultBinDir({ PATH: "/usr/bin:/bin", HOME: root }),
    path.join(root, ".local", "bin")
  );
});

test("stable entry invokes pinned Node and CLI with no version manager in minimal PATH", (t) => {
  const { stableBin, node, cli } = fixture(t);
  const minimalPath = `${stableBin}:/usr/bin:/bin`;
  const options = { nodePath: node, cliPath: cli, binDir: stableBin, env: { PATH: minimalPath } };
  const installed = installSystemEntry(options);
  assert.equal(installed.changed, true);
  assert.equal(installed.path, path.join(stableBin, "asvc"));
  assert.equal(installed.binDirOnPath, true);
  assert.equal(installSystemEntry(options).changed, false);

  const content = fs.readFileSync(installed.path, "utf8");
  assert.doesNotMatch(content, /asdf|nvm|fnm|volta/i);

  const env = { PATH: minimalPath };
  const version = spawnSync("asvc", ["--version"], { env, encoding: "utf8" });
  const list = spawnSync("asvc", ["list"], { env, encoding: "utf8" });
  assert.equal(version.status, 0, version.stderr);
  assert.equal(version.stdout, "resolved:--version\n");
  assert.equal(list.status, 0, list.stderr);
  assert.equal(list.stdout, "resolved:list\n");
});

test("stable entry upgrades an older managed asdf entry without force", (t) => {
  const { stableBin, node, cli } = fixture(t);
  const target = path.join(stableBin, "asvc");
  fs.writeFileSync(
    target,
    '#!/bin/sh\n# Generated by @homeant/asvc setup-entry\nexec /opt/homebrew/bin/asdf exec asvc "$@"\n',
    { mode: 0o755 }
  );

  const result = installSystemEntry({ nodePath: node, cliPath: cli, binDir: stableBin });
  assert.equal(result.changed, true);
  assert.equal(fs.readFileSync(target, "utf8"), buildSystemEntry(node, cli));
});

test("stable entry refuses to replace an unrelated command without force", (t) => {
  const { stableBin, node, cli } = fixture(t);
  fs.writeFileSync(path.join(stableBin, "asvc"), "foreign\n", { mode: 0o755 });

  assert.throws(
    () => installSystemEntry({ nodePath: node, cliPath: cli, binDir: stableBin }),
    /目标已存在/
  );
  const result = installSystemEntry({
    nodePath: node,
    cliPath: cli,
    binDir: stableBin,
    force: true,
  });
  assert.equal(result.changed, true);
  assert.equal(fs.readFileSync(result.path, "utf8"), buildSystemEntry(node, cli));
});
