import fs from "node:fs";
import path from "node:path";

const ENTRY_MARKER = "# Generated by @homeant/asvc setup-entry";

export interface InstallSystemEntryOptions {
  /** Override the target directory. By default install next to the active asdf executable. */
  binDir?: string;
  /** Override executable discovery, primarily for tests. */
  asdfPath?: string;
  env?: NodeJS.ProcessEnv;
  force?: boolean;
}

export interface InstallSystemEntryResult {
  path: string;
  asdfPath: string;
  changed: boolean;
}

/** Resolve an executable from PATH without invoking a login shell or user profile. */
export function findExecutable(
  name: string,
  env: NodeJS.ProcessEnv = process.env
): string | undefined {
  for (const dir of (env.PATH ?? "").split(path.delimiter)) {
    if (!dir) continue;
    const candidate = path.join(dir, name);
    try {
      fs.accessSync(candidate, fs.constants.X_OK);
      if (fs.statSync(candidate).isFile()) return candidate;
    } catch {
      /* not executable */
    }
  }
  return undefined;
}

/**
 * Generate a stable entry that delegates selection back to asdf for the caller's cwd.
 * The detected asdf path is absolute, but no user home or Node.js version is embedded.
 */
export function buildSystemEntry(asdfPath: string): string {
  return [
    "#!/bin/sh",
    ENTRY_MARKER,
    `exec ${shellQuote(asdfPath)} exec asvc "$@"`,
    "",
  ].join("\n");
}

export function installSystemEntry(
  options: InstallSystemEntryOptions = {}
): InstallSystemEntryResult {
  const env = options.env ?? process.env;
  const asdfPath = path.resolve(
    options.asdfPath ??
      findExecutable("asdf", env) ??
      missingAsdf()
  );
  const binDir = path.resolve(options.binDir ?? path.dirname(asdfPath));
  const target = path.join(binDir, "asvc");
  const content = buildSystemEntry(asdfPath);

  let current: string | undefined;
  try {
    current = fs.readFileSync(target, "utf8");
  } catch (err) {
    if (!isMissing(err)) throw err;
  }

  if (current === content) {
    return { path: target, asdfPath, changed: false };
  }
  if (current !== undefined && !options.force) {
    throw new Error(
      `目标已存在且不是当前 asvc 稳定入口: ${target}\n` +
        "如确认要替换，请重新执行并添加 --force。"
    );
  }

  fs.mkdirSync(binDir, { recursive: true });
  const temporary = path.join(binDir, `.asvc-entry-${process.pid}-${Date.now()}.tmp`);
  try {
    fs.writeFileSync(temporary, content, { encoding: "utf8", mode: 0o755, flag: "wx" });
    fs.renameSync(temporary, target);
    fs.chmodSync(target, 0o755);
  } finally {
    try {
      fs.unlinkSync(temporary);
    } catch {
      /* already renamed or never created */
    }
  }

  return { path: target, asdfPath, changed: true };
}

function shellQuote(value: string): string {
  return `'${value.replaceAll("'", `'\\''`)}'`;
}

function missingAsdf(): never {
  throw new Error(
    "PATH 中找不到 asdf。请先让 asdf CLI 在当前非登录 shell 中可执行，再安装稳定入口。"
  );
}

function isMissing(err: unknown): boolean {
  return err instanceof Error && "code" in err && err.code === "ENOENT";
}
