import { execFileSync } from "node:child_process";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";

const ENTRY_MARKER = "# Generated by @homeant/asvc setup-entry";

export interface InstallSystemEntryOptions {
  /** Override the target directory. */
  binDir?: string;
  /** Pin the Node executable which is running setup-entry. */
  nodePath?: string;
  /** Pin the installed asvc CLI module. */
  cliPath: string;
  env?: NodeJS.ProcessEnv;
  force?: boolean;
}

export interface InstallSystemEntryResult {
  path: string;
  nodePath: string;
  cliPath: string;
  changed: boolean;
  binDirOnPath: boolean;
}

/** Resolve an executable from PATH without invoking a login shell or user profile. */
export function findExecutable(
  name: string,
  env: NodeJS.ProcessEnv = process.env
): string | undefined {
  for (const dir of (env.PATH ?? "").split(path.delimiter)) {
    if (!dir) continue;
    const candidate = path.join(dir, name);
    try {
      fs.accessSync(candidate, fs.constants.X_OK);
      if (fs.statSync(candidate).isFile()) return candidate;
    } catch {
      /* not executable */
    }
  }
  return undefined;
}

/**
 * Select a manager-neutral command directory. Homebrew's bin is normally already present in
 * non-login PATHs; otherwise use the conventional per-user bin directory.
 */
export function resolveDefaultBinDir(
  env: NodeJS.ProcessEnv = process.env
): string {
  const brew = findExecutable("brew", env);
  if (brew) {
    try {
      const prefix = execFileSync(brew, ["--prefix"], {
        encoding: "utf8",
        env,
        stdio: ["ignore", "pipe", "ignore"],
      }).trim();
      if (prefix) return path.resolve(prefix, "bin");
    } catch {
      /* fall through to a per-user location */
    }
  }

  if (env.XDG_BIN_HOME) return path.resolve(env.XDG_BIN_HOME);
  return path.join(env.HOME ? path.resolve(env.HOME) : os.homedir(), ".local", "bin");
}

/**
 * Generate an entry independent of asdf, nvm, fnm, Volta, or any other version manager.
 * setup-entry records the actual Node executable and installed CLI which are already running.
 */
export function buildSystemEntry(nodePath: string, cliPath: string): string {
  const node = shellQuote(path.resolve(nodePath));
  const cli = shellQuote(path.resolve(cliPath));
  return [
    "#!/bin/sh",
    ENTRY_MARKER,
    `ASVC_NODE=${node}`,
    `ASVC_CLI=${cli}`,
    'if [ ! -x "$ASVC_NODE" ]; then',
    '  echo "asvc: pinned Node executable is unavailable: $ASVC_NODE" >&2',
    '  echo "asvc: load any available Node installation and rerun: asvc setup-entry" >&2',
    "  exit 127",
    "fi",
    'if [ ! -f "$ASVC_CLI" ]; then',
    '  echo "asvc: pinned CLI module is unavailable: $ASVC_CLI" >&2',
    '  echo "asvc: reinstall @homeant/asvc and rerun setup-entry" >&2',
    "  exit 127",
    "fi",
    'exec "$ASVC_NODE" "$ASVC_CLI" "$@"',
    "",
  ].join("\n");
}

export function installSystemEntry(
  options: InstallSystemEntryOptions
): InstallSystemEntryResult {
  const env = options.env ?? process.env;
  const nodePath = path.resolve(options.nodePath ?? process.execPath);
  const cliPath = path.resolve(options.cliPath);
  const binDir = path.resolve(options.binDir ?? resolveDefaultBinDir(env));
  const target = path.join(binDir, "asvc");
  const content = buildSystemEntry(nodePath, cliPath);

  let current: string | undefined;
  try {
    current = fs.readFileSync(target, "utf8");
  } catch (err) {
    if (!isMissing(err)) throw err;
  }

  const result = (changed: boolean): InstallSystemEntryResult => ({
    path: target,
    nodePath,
    cliPath,
    changed,
    binDirOnPath: pathEntries(env).includes(binDir),
  });

  if (current === content) return result(false);
  if (current !== undefined && !current.includes(ENTRY_MARKER) && !options.force) {
    throw new Error(
      `目标已存在且不是 asvc 管理的稳定入口: ${target}\n` +
        "如确认要替换，请重新执行并添加 --force。"
    );
  }

  fs.mkdirSync(binDir, { recursive: true });
  const temporary = path.join(binDir, `.asvc-entry-${process.pid}-${Date.now()}.tmp`);
  try {
    fs.writeFileSync(temporary, content, { encoding: "utf8", mode: 0o755, flag: "wx" });
    fs.renameSync(temporary, target);
    fs.chmodSync(target, 0o755);
  } finally {
    try {
      fs.unlinkSync(temporary);
    } catch {
      /* already renamed or never created */
    }
  }

  return result(true);
}

function pathEntries(env: NodeJS.ProcessEnv): string[] {
  return (env.PATH ?? "")
    .split(path.delimiter)
    .filter(Boolean)
    .map((entry) => path.resolve(entry));
}

function shellQuote(value: string): string {
  return `'${value.replaceAll("'", `'\\''`)}'`;
}

function isMissing(err: unknown): boolean {
  return err instanceof Error && "code" in err && err.code === "ENOENT";
}
